In [1]:
import plotly.io as pio
import plotly.express as px

pio.templates.default = "plotly_white"
COLOUR_CONTINIOUS_SCALE="bluered"

# The one bellow should be both color-blind and print friendly. It's based on: https://colorbrewer2.org/#type=sequential&scheme=RdPu&n=5
COLOUR_ARRAY = ["#feebe2", "#fbb4b9", "#f768a1", "#c51b8a", "#7a0177"]

pio.renderers.default = 'iframe'
import pandas as pd

In [2]:
# These 9 dialogues contain more than 50% correct answers in the solo submissions
# exclude_9_correct = ["ec8896c6-56fb-4187-a932-92ac6bbd6f49", "c47d75d6-98f9-4a03-a0b1-54b341849ffc", "e731d8d4-d6f3-44ca-9d04-0d2caa2f0111", "02972b77-c909-499e-8d4b-8920a25707f0", "b1d5c668-eb55-440a-ade6-155784bcd0a4", "28e38a3c-0298-4585-b05f-cef4968f56c1", "f052602b-0dbe-45f8-8407-f0887616ad41", "dca3b7c4-9483-4d9d-b76b-b7244cd8529a", "513c227d-c2c2-4eb6-8730-feb1d513cbc1"]
exclude_9_correct = []

In [3]:
df=pd.read_csv('meta_stats.tsv',sep='\t')
mask = df['room'].isin(exclude_9_correct)
df = df[~mask]

In [4]:
df

,Unnamed: 0,room,message_count,num_of_players,onboarding_success_rate,final_success_rate,onboarding_types,onboarding_types_fine,game_types,final_agreement,...,final_success_rate_coarse,deli_correct,moderator_messages,submits_per_user,performance_gain,unique_tokens_count,tokens_count,submits_per_user.1,message_entropy,best_onboarding_score
0,7c3f79ae-33a6-432b-941f-c7daa6047456,7c3f79ae-33a6-432b-941f-c7daa6047456,25,5,0.4500,0.6000,"Counter({'OTHER_ERROR': 3, 'BIASED': 2})","Counter({'E2': 2, '2': 2, 'E': 1})","Counter({'BIASED': 4, 'CORRECT': 1})",0.80,...,0.20,1,0,1.20,0.1500,71,176,1.20,0.974546,0.75
1,ebc07608-c97c-489c-b541-0206fbd69ff3,ebc07608-c97c-489c-b541-0206fbd69ff3,16,3,0.5000,0.7500,"Counter({'OTHER_ERROR': 2, 'BIASED': 1})","Counter({'H': 1, 'A': 1, '2A': 1})",Counter({'OTHER_ERROR': 3}),1.00,...,0.00,0,0,1.00,0.2500,39,126,1.00,0.996512,0.75
2,4bb4ff7d-1479-4f85-99ee-5014cbb72c0e,4bb4ff7d-1479-4f85-99ee-5014cbb72c0e,33,4,0.5000,0.6250,"Counter({'OTHER_ERROR': 2, 'BIASED': 2})","Counter({'U8': 2, '3': 1, '8': 1})","Counter({'BIASED': 3, 'CORRECT': 1})",0.75,...,0.25,1,0,1.00,0.1250,76,244,1.00,0.991113,0.75
3,08c890ac-c67f-4be7-aaba-8c3f31c8abc1,08c890ac-c67f-4be7-aaba-8c3f31c8abc1,26,4,0.5000,1.0000,"Counter({'OTHER_ERROR': 2, 'ALL_CHECKED': 1, '...","Counter({'W9E6': 1, 'E6': 1, '6': 1, 'E': 1})",Counter({'CORRECT': 4}),1.00,...,1.00,1,0,1.75,0.5000,89,355,1.75,0.961012,0.75
4,b7cf985f-3c55-4ea1-a2fe-8b76e4357e00,b7cf985f-3c55-4ea1-a2fe-8b76e4357e00,61,5,0.6000,1.0000,"Counter({'OTHER_ERROR': 3, 'BIASED': 1, 'BIASE...","Counter({'5Z': 2, 'A2': 1, 'A': 1, 'A25': 1})",Counter({'CORRECT': 5}),1.00,...,1.00,1,0,1.00,0.4000,105,433,1.00,0.884817,0.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,3deba349-01dd-46f5-a1be-dbe3268b53ce,3deba349-01dd-46f5-a1be-dbe3268b53ce,29,5,0.4500,0.5000,"Counter({'BIASED': 2, 'OTHER_ERROR': 2, 'BIASE...","Counter({'E2': 2, 'H': 2, 'E52': 1})",Counter({'BIASED': 5}),1.00,...,0.00,0,0,1.40,0.0500,67,277,1.40,0.914775,0.75
496,e2c29822-1f0a-43dd-bed8-6ee52416ea18,e2c29822-1f0a-43dd-bed8-6ee52416ea18,34,4,0.5625,0.6875,"Counter({'OTHER_ERROR': 1, 'ALL_CHECKED': 1, '...","Counter({'EG': 1, '25EG': 1, '25E': 1, '2E': 1})","Counter({'BIASED + ODDS': 2, 'OTHER_ERROR': 1,...",0.50,...,0.25,1,0,1.00,0.1250,70,452,1.00,0.957023,0.75
497,7df3735d-927e-4055-81e6-8ed925e56649,7df3735d-927e-4055-81e6-8ed925e56649,45,4,0.5625,1.0000,"Counter({'BIASED': 2, 'CORRECT': 1, 'OTHER_ERR...","Counter({'8E': 2, 'E9': 1, '8': 1})",Counter({'CORRECT': 4}),0.75,...,1.00,0,0,1.50,0.4375,97,494,1.50,0.962522,1.00
498,a6cb47d1-4ba5-4093-9ab1-5ab12e4d0863,a6cb47d1-4ba5-4093-9ab1-5ab12e4d0863,11,2,0.5000,0.6250,Counter({'OTHER_ERROR': 2}),"Counter({'E': 1, '94M': 1})","Counter({'OTHER_ERROR': 1, 'BIASED': 1})",0.50,...,0.00,0,0,2.00,0.1250,31,84,2.00,0.994030,0.75
499,8b831534-658f-4288-ba5f-c50f6a4b6638,8b831534-658f-4288-ba5f-c50f6a4b6638,18,2,0.6250,1.0000,"Counter({'BIASED': 1, 'OTHER_ERROR': 1})","Counter({'4E': 1, '3': 1})",Counter({'CORRECT': 2}),1.00,...,1.00,1,0,1.00,0.3750,50,156,1.00,1.000000,0.75

In [5]:
df[df['performance_gain'] == 0]

,Unnamed: 0,room,message_count,num_of_players,onboarding_success_rate,final_success_rate,onboarding_types,onboarding_types_fine,game_types,final_agreement,...,final_success_rate_coarse,deli_correct,moderator_messages,submits_per_user,performance_gain,unique_tokens_count,tokens_count,submits_per_user.1,message_entropy,best_onboarding_score
9,d799b708-dffb-42bf-b10d-12b82fd074c3,d799b708-dffb-42bf-b10d-12b82fd074c3,7,2,0.500000,0.500000,Counter({'ALL_CHECKED': 2}),Counter({'4AG9': 2}),Counter({'ALL_CHECKED': 2}),1.000000,...,0.000000,0,0,1.000000,0.0,56,128,1.000000,0.863121,0.50
21,2e4ec628-8c4d-4058-83b0-f7142240fe7e,2e4ec628-8c4d-4058-83b0-f7142240fe7e,21,3,0.500000,0.500000,"Counter({'OTHER_ERROR': 2, 'BIASED': 1})","Counter({'G': 1, '2A': 1, '7': 1})",Counter({'BIASED': 3}),1.000000,...,0.000000,0,0,2.000000,0.0,15,79,2.000000,0.889595,0.75
35,862b4320-b1df-4ae1-a539-61023911edf1,862b4320-b1df-4ae1-a539-61023911edf1,26,3,0.833333,0.833333,"Counter({'OTHER_ERROR': 2, 'CORRECT': 1})","Counter({'E': 2, '3E': 1})","Counter({'BIASED + ODDS': 2, 'CORRECT': 1})",0.666667,...,0.333333,0,0,1.333333,0.0,79,189,1.333333,0.947679,1.00
39,4055602f-dfa6-4046-bcab-777bc97471a1,4055602f-dfa6-4046-bcab-777bc97471a1,7,2,0.500000,0.500000,"Counter({'BIASED': 1, 'ALL_CHECKED': 1})","Counter({'6A': 1, '6HA9': 1})",Counter({'BIASED': 2}),1.000000,...,0.000000,0,0,1.000000,0.0,46,118,1.000000,0.985228,0.50
42,338c2869-0ab3-4400-b086-014788358786,338c2869-0ab3-4400-b086-014788358786,7,2,0.500000,0.500000,"Counter({'BIASED': 1, 'OTHER_ERROR': 1})","Counter({'2A': 1, 'Z3': 1})","Counter({'ALL_CHECKED': 1, 'OTHER_ERROR': 1})",0.500000,...,0.000000,0,0,1.000000,0.0,39,145,1.000000,0.985228,0.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
479,d0baa63b-5b52-46af-863f-ce7da29a1bd4,d0baa63b-5b52-46af-863f-ce7da29a1bd4,27,2,0.750000,0.750000,"Counter({'CORRECT': 1, 'BIASED': 1})","Counter({'3A': 1, '8A': 1})","Counter({'CORRECT': 1, 'BIASED': 1})",0.500000,...,0.500000,0,0,1.000000,0.0,68,220,1.000000,0.950956,1.00
487,0fe49822-69a3-488b-856d-436cb9d8d45f,0fe49822-69a3-488b-856d-436cb9d8d45f,17,2,0.750000,0.750000,"Counter({'CORRECT': 1, 'BIASED': 1})","Counter({'A1': 1, 'A4': 1})","Counter({'CORRECT': 1, 'BIASED': 1})",0.500000,...,0.500000,0,0,1.000000,0.0,60,258,1.000000,0.997503,1.00
488,8aa706ab-08f8-44d9-85ec-073f88ba0a5b,8aa706ab-08f8-44d9-85ec-073f88ba0a5b,20,2,0.750000,0.750000,"Counter({'CORRECT': 1, 'BIASED': 1})","Counter({'E5': 1, '2E': 1})","Counter({'CORRECT': 1, 'BIASED': 1})",0.500000,...,0.500000,0,0,1.000000,0.0,80,306,1.000000,0.992774,1.00
491,aef4972a-02f2-4deb-9af4-b242943ed964,aef4972a-02f2-4deb-9af4-b242943ed964,31,4,0.375000,0.375000,"Counter({'OTHER_ERROR': 2, 'BIASED': 1, 'ALL_I...","Counter({'U4': 1, 'U': 1, '4Z': 1, 'Z': 1})",Counter({'OTHER_ERROR': 4}),0.750000,...,0.000000,0,0,1.000000,0.0,64,209,1.000000,0.931155,0.75
492,a33d18c2-c556-4e25-b2b5-0d87ee33cc9f,a33d18c2-c556-4e25-b2b5-0d87ee33cc9f,27,3,0.416667,0.416667,"Counter({'OTHER_ERROR': 2, 'ALL_CHECKED': 1})","Counter({'6': 1, '69': 1, '69EB': 1})","Counter({'ALL_CHECKED': 2, 'BIASED + CONST': 1})",0.666667,...,0.000000,0,0,1.000000,0.0,48,141,1.000000,0.912674,0.50

In [6]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [7]:

fig = go.Figure()

fig.add_trace(go.Violin(y=df[df['num_of_players']==2]['message_count'],
                        name='Utterance Count',
                        side='negative', legendgroup='Dyads', scalegroup='Dyads', showlegend=False,
                        line_color=COLOUR_ARRAY[2], points=False)
             )
fig.add_trace(go.Violin(y=df[df['num_of_players']>=3]['message_count'],
                        name='Utterance Count',legendgroup='Groups', scalegroup='Groups',  showlegend=False,
                        side='positive',
                        line_color=COLOUR_ARRAY[4], points=False)
             )

fig.add_trace(go.Violin(y=df[df['num_of_players']==2]['unique_tokens_count'],
                        name='Unique Tokens',
                        side='negative', legendgroup='Dyads', scalegroup='Dyads', showlegend=False,
                        line_color=COLOUR_ARRAY[2], points=False)
             )
fig.add_trace(go.Violin(y=df[df['num_of_players']>=3]['unique_tokens_count'],
                        name='Unique Tokens',legendgroup='Groups', scalegroup='Groups',  showlegend=False,
                        side='positive',
                        line_color=COLOUR_ARRAY[4], points=False)
             )
fig.update_traces(meanline_visible=True)
fig.add_trace(go.Scatter(
    x=[None], 
    y=[None],
    mode='markers',
    line=dict(color=COLOUR_ARRAY[2]),
    name='Dyads',
))

fig.add_trace(go.Scatter(
    x=[None], 
    y=[None],
    mode='markers',
    line=dict(color=COLOUR_ARRAY[4]),
    name='Groups'
))
fig.update_layout(legend= {'itemsizing': 'constant'})

fig.update_layout(violingap=0.3, violinmode='overlay')
fig.update_layout(font_size=20)

fig.show()

In [8]:
import plotly.io as pio

# Set the scale factor for resolution
# scale=1 corresponds to 96 dpi, scale=2 corresponds to 192 dpi, scale=3 corresponds to 288 dpi, and so on.
scale = 6  # Adjust this to control the resolution

filename = "violin_dyads_groups_tokens_messages.png"
pio.write_image(fig, filename, format='png', scale=scale)

In [9]:
import scipy.stats as stats

#perform one sample t-test
print(stats.ttest_1samp(a=df[df['num_of_players']==2]['performance_gain'].tolist(), popmean=0))
print(stats.ttest_1samp(a=df[df['num_of_players']==3]['performance_gain'].tolist(), popmean=0))
print(stats.ttest_1samp(a=df[df['num_of_players']==4]['performance_gain'].tolist(), popmean=0))
print(stats.ttest_1samp(a=df[df['num_of_players']==5]['performance_gain'].tolist(), popmean=0))

TtestResult(statistic=5.900457696778942, pvalue=2.51064371215885e-08, df=143)
TtestResult(statistic=8.56614966300631, pvalue=3.544327034552694e-15, df=191)
TtestResult(statistic=7.812757033248455, pvalue=4.0923644428031146e-12, df=107)
TtestResult(statistic=7.787640506093395, pvalue=2.760553323360274e-10, df=52)

In [10]:
fig = go.Figure([go.Scatter(
        x=[2, 3, 4, 5],
        y=[
        df[df['num_of_players']==2]['performance_gain'].mean(),
        df[df['num_of_players']==3]['performance_gain'].mean(),
        df[df['num_of_players']==4]['performance_gain'].mean(),
        df[df['num_of_players']==5]['performance_gain'].mean()],
        error_y=dict(
            type='data', # value of error bar given in data coordinates
            array=[
                  df[df['num_of_players']==2]['performance_gain'].sem(),
        df[df['num_of_players']==3]['performance_gain'].sem(),
        df[df['num_of_players']==4]['performance_gain'].sem(),
        df[df['num_of_players']==5]['performance_gain'].sem()
                  ],
            visible=True), line_color=COLOUR_ARRAY[4]
    ),])
fig.add_hline(y=0, line_dash="dash", line_color=COLOUR_ARRAY[3], line_width=4)

fig.update_xaxes(nticks=4, title="Number of participants")
fig.update_yaxes(title="Performance Gain") # TODO: add baseline of 0

fig.update_layout(yaxis_range=[-0.05,0.25])

fig.update_layout(font_size=20)

fig.show()

In [11]:
import plotly.io as pio

# Set the scale factor for resolution
# scale=1 corresponds to 96 dpi, scale=2 corresponds to 192 dpi, scale=3 corresponds to 288 dpi, and so on.
scale = 6  # Adjust this to control the resolution

filename = "scatter_performance_gains.png"
pio.write_image(fig, filename, format='png', scale=scale)

In [12]:
from scipy.stats import f_oneway, ttest_ind

In [13]:
f_oneway(df[df['num_of_players']==2]['performance_gain'],
        df[df['num_of_players']==3]['performance_gain'],
        df[df['num_of_players']==4]['performance_gain'],
        df[df['num_of_players']==5]['performance_gain'])

F_onewayResult(statistic=3.1387797825171337, pvalue=0.02513039202829832)

In [14]:
print("2|3 " + str(ttest_ind(df[df['num_of_players']==2]['performance_gain'],  df[df['num_of_players']==3]['performance_gain'])[1]))
print("3|4 " + str(ttest_ind(df[df['num_of_players']==3]['performance_gain'],  df[df['num_of_players']==4]['performance_gain'])[1]))
print("4|5 " + str(ttest_ind(df[df['num_of_players']==4]['performance_gain'],  df[df['num_of_players']==5]['performance_gain'])[1]))
print("2|3+ " + str(ttest_ind(df[df['num_of_players']==2]['performance_gain'],  df[df['num_of_players']>=3]['performance_gain'])[1]))

2|3 0.17163895105523086
3|4 0.7497777637190792
4|5 0.061736343039673305
2|3+ 0.02685260542116774

In [15]:
import ast

In [16]:
a = ast.literal_eval("Counter({'OTHER_ERROR': 3, 'BIASED': 2})"[8:-1])

In [17]:
from collections import defaultdict

In [18]:
biased = []
diverse = []
contain_correct = []
contain_correct_and_diverse = []

for _, item in df.iterrows():
    solo_submissions_fine = ast.literal_eval(item['onboarding_types_fine'][8:-1])
    solo_submissions =  ast.literal_eval(item['onboarding_types'][8:-1])
    df.at[_, 'diversity'] = len(solo_submissions_fine)

    if item['num_of_players'] == 2:
        continue
    if len(solo_submissions_fine) <= 2 and 'CORRECT' not in solo_submissions:
        biased.append(item['performance_gain'])
    if len(solo_submissions_fine) >=4 and 'CORRECT' not in solo_submissions:
        diverse.append(item['performance_gain'])
    if 'CORRECT' in solo_submissions and len(solo_submissions_fine) <= 2:
        contain_correct.append(item['performance_gain'])
        
    if 'CORRECT' in solo_submissions and len(solo_submissions_fine) >=4:
        contain_correct_and_diverse.append(item['performance_gain'])

print(len(diverse))
print(len(contain_correct_and_diverse))

36
24

In [19]:

all_pgs = []
for item in contain_correct_and_diverse:
    all_pgs.append([1, 1, item])
for item in contain_correct:
    all_pgs.append([0, 1, item])
for item in diverse:
    all_pgs.append([1, 0, item])
for item in biased:
    all_pgs.append([0, 0, item])

In [20]:
len(all_pgs)

177

In [21]:
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm

In [22]:
df_new = pd.DataFrame(all_pgs, columns=['diverse', 'correct', 'pg'])
df_new.describe()

          diverse     correct          pg
count  177.000000  177.000000  177.000000
mean     0.338983    0.282486    0.129567
std      0.474707    0.451486    0.180860
min      0.000000    0.000000   -0.666667
25%      0.000000    0.000000    0.000000
50%      0.000000    0.000000    0.125000
75%      1.000000    1.000000    0.250000
max      1.000000    1.000000    0.583333

In [23]:
from scipy.stats import zscore

In [24]:
df_new[['diverse']] = df_new[['diverse']].transform(lambda x: zscore(x))
df_new[['correct']] = df_new[['correct']].transform(lambda x: zscore(x))

df_new[['pg']] = df_new[['pg']].transform(lambda x: zscore(x))

In [25]:
all_trans = ols("pg ~ diverse  + correct", data=df_new).fit()
all_trans.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                     pg   R-squared:                       0.091
Model:                            OLS   Adj. R-squared:                  0.081
Method:                 Least Squares   F-statistic:                     8.728
Date:                Thu, 01 Feb 2024   Prob (F-statistic):           0.000244
Time:                        20:49:05   Log-Likelihood:                -242.69
No. Observations:                 177   AIC:                             491.4
Df Residuals:                     174   BIC:                             500.9
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -7.806e-18      0.072  -1.08e-16      1.000      -0.143       0.143
diverse        0.2493      0.074      3.389      0.001       0.104       0.395
correct        0.1300      0.074      1.767      0.079      -0.015       0.275
==============================================================================
Omnibus:                       10.243   Durbin-Watson:                   1.997
Prob(Omnibus):                  0.006   Jarque-Bera (JB):               23.099
Skew:                           0.048   Prob(JB):                     9.64e-06
Kurtosis:                       4.767   Cond. No.                         1.21
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [26]:

fig = go.Figure()




fig.add_trace(go.Box(y=biased, boxpoints=False, name="Low Diversity <br> (no correct)   ", notched=True, marker_color=COLOUR_ARRAY[2]))
fig.add_trace(go.Box(y=diverse, boxpoints=False, name="High Diversity <br> (no correct)", notched=True, marker_color=COLOUR_ARRAY[4]))

fig.add_trace(go.Box(y=contain_correct, boxpoints=False, name="Low Diversity <br> (with correct)", notched=True, marker_color=COLOUR_ARRAY[2]))
fig.add_trace(go.Box(y=contain_correct_and_diverse, boxpoints=False, name="High Diversity <br> (with correct)", notched=True, marker_color=COLOUR_ARRAY[4]))
fig.update(layout_showlegend=False)
fig.update_layout(font_size=26)
fig.update_xaxes(tickangle=0)  
fig.update_layout(bargap=1)
fig.update_layout(width = 1000)
fig.show()

In [27]:
import plotly.io as pio

# Set the scale factor for resolution
# scale=1 corresponds to 96 dpi, scale=2 corresponds to 192 dpi, scale=3 corresponds to 288 dpi, and so on.
scale = 6  # Adjust this to control the resolution

filename = "solo_diversity.png"
pio.write_image(fig, filename, format='png', scale=scale)

# Comparing diversity

In [28]:
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm

In [29]:
players = ols("performance_gain ~ num_of_players", data=df).fit()
players_diverse = ols("performance_gain ~ diversity + num_of_players", data=df).fit()
anova_lm(players, players_diverse)

   df_resid        ssr  df_diff   ss_diff          F    Pr(>F)
0     498.0  18.678242      0.0       NaN        NaN       NaN
1     497.0  18.243058      1.0  0.435184  11.855822  0.000623

In [30]:
diverse = ols("performance_gain ~ diversity", data=df).fit()
players_diverse = ols("performance_gain ~ diversity + num_of_players", data=df).fit()
anova_lm(diverse, players_diverse)

   df_resid        ssr  df_diff  ss_diff         F    Pr(>F)
0     498.0  18.245167      0.0      NaN       NaN       NaN
1     497.0  18.243058      1.0  0.00211  0.057472  0.810635